# Generated by Django 5.2.4 on 2025-07-13 04:35

from django.db import migrations

def update_nicknames(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for student in CustomUser.objects.filter(role='student'):
        if not student.nickname or student.nickname.startswith("Student_"):
            student.nickname = f"Student_{student.id}"
            student.save(update_fields=['nickname'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_nicknames),
    ]
