# Generated by Django 5.2.4 on 2025-07-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_credit_customuser_num_good_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_answers_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_question_resolved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]
