# Generated by Django 5.2.4 on 2025-07-18 05:39
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_num_answers_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='num_answers_given',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='num_question_resolved',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='num_questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]