# Generated by Django 5.2.4 on 2025-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250718_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_answers_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_question_resolved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]
