# Generated by Django 5.2.4 on 2025-07-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_num_answers_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='num_question_resolved',
        ),
    ]
