# Generated by Django 5.2.4 on 2025-07-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='anonymous',
        ),
    ]
