# Generated by Django 5.2.4 on 2025-07-15 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_subjects(apps, schema_editor):
    Subject = apps.get_model('qa', 'Subject')
    subjects = [
        ('IG_Maths', 'IG Maths'),
        ('ESL', 'English as Second Language'),
        ('CFL', 'Chinese as First Language'),
        ('IG_Bio', 'IG Biology'),
        ('IG_Chem', 'IG Chemistry'),
        ('IG_Phy', 'IG Physics'),
        ('IG_Hist', 'IG History'),
        ('IG_Geo', 'IG Geography'),
        ('IG_Econ', 'IG Economics'),
        ('IG_Acc', 'IG Accounting'),
        ('IG_CS', 'IG Computer Science'),
        ('IG_Socio', 'IG Sociology'),
        ('IG_Bus', 'IG Business Studies'),
        ('AS_Bio', 'AS Biology'),
        ('AS_Chem', 'AS Chemistry'),
        ('AS_Phy', 'AS Physics'),
        ('AS_PM1', 'AS Pure Maths 1'),
        ('AS_PM2', 'AS Pure Maths 2'),
        ('AS_Mech1', 'AS Mechanics 1'),
        ('AS_Prob1', 'AS Prob & Stats 1'),
        ('AS_Econ', 'AS Economics'),
        ('AS_Acc', 'AS Accounting'),
        ('AS_CS', 'AS Computer Science'),
        ('AS_Socio', 'AS Sociology'),
        ('AS_Hist', 'AS History'),
        ('AS_Geo', 'AS Geography'),
        ('AS_Bus', 'AS Business Studies'),
        ('EFL', 'English as First Language'),
        ('FP1', 'Edexcel FP1'),
        ('FP2', 'Edexcel FP2'),
        ('DM1', 'Edexcel Decision Maths 1'),
        ('A2_Bio', 'A2 Biology'),
        ('A2_Chem', 'A2 Chemistry'),
        ('A2_Phy', 'A2 Physics'),
        ('A2_PM3', 'A2 Pure Maths 3'),
        ('A2_Mech2', 'A2 Mechanics 2'),
        ('A2_Prob2', 'A2 Prob & Stats 2'),
        ('A2_Econ', 'A2 Economics'),
        ('A2_Acc', 'A2 Accounting'),
        ('A2_CS', 'A2 Computer Science'),
        ('A2_Socio', 'A2 Sociology'),
        ('A2_Hist', 'A2 History'),
        ('A2_Geo', 'A2 Geography'),
        ('A2_Bus', 'A2 Business Studies'),
        ('Eng_Lit', 'English Literature'),
        ('FP3', 'Edexcel FP3'),
        ('FS1', 'Edexcel Further Stats 1'),
        ('FM1', 'Edexcel Further Mech 1'),
    ]
    
    for code, name in subjects:
        Subject.objects.create(name=code)

def create_years(apps, schema_editor):
    YearGroup = apps.get_model('qa', 'YearGroup')
    for year in range(8, 13):
        YearGroup.objects.create(year=year)

class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_answer_options_remove_answer_anonymous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IG_Maths', 'IG Maths'), ('ESL', 'English as Second Language'), ('CFL', 'Chinese as First Language'), ('IG_Bio', 'IG Biology'), ('IG_Chem', 'IG Chemistry'), ('IG_Phy', 'IG Physics'), ('IG_Hist', 'IG History'), ('IG_Geo', 'IG Geography'), ('IG_Econ', 'IG Economics'), ('IG_Acc', 'IG Accounting'), ('IG_CS', 'IG Computer Science'), ('IG_Socio', 'IG Sociology'), ('IG_Bus', 'IG Business Studies'), ('AS_Bio', 'AS Biology'), ('AS_Chem', 'AS Chemistry'), ('AS_Phy', 'AS Physics'), ('AS_PM1', 'AS Pure Maths 1'), ('AS_PM2', 'AS Pure Maths 2'), ('AS_Mech1', 'AS Mechanics 1'), ('AS_Prob1', 'AS Prob & Stats 1'), ('AS_Econ', 'AS Economics'), ('AS_Acc', 'AS Accounting'), ('AS_CS', 'AS Computer Science'), ('AS_Socio', 'AS Sociology'), ('AS_Hist', 'AS History'), ('AS_Geo', 'AS Geography'), ('AS_Bus', 'AS Business Studies'), ('EFL', 'English as First Language'), ('FP1', 'Edexcel FP1'), ('FP2', 'Edexcel FP2'), ('DM1', 'Edexcel Decision Maths 1'), ('A2_Bio', 'A2 Biology'), ('A2_Chem', 'A2 Chemistry'), ('A2_Phy', 'A2 Physics'), ('A2_PM3', 'A2 Pure Maths 3'), ('A2_Mech2', 'A2 Mechanics 2'), ('A2_Prob2', 'A2 Prob & Stats 2'), ('A2_Econ', 'A2 Economics'), ('A2_Acc', 'A2 Accounting'), ('A2_CS', 'A2 Computer Science'), ('A2_Socio', 'A2 Sociology'), ('A2_Hist', 'A2 History'), ('A2_Geo', 'A2 Geography'), ('A2_Bus', 'A2 Business Studies'), ('Eng_Lit', 'English Literature'), ('FP3', 'Edexcel FP3'), ('FS1', 'Edexcel Further Stats 1'), ('FM1', 'Edexcel Further Mech 1')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='qa.subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_subjects', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_taught', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.yeargroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.subject')),
            ],
            options={
                'unique_together': {('student', 'year', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_subjects', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.yeargroup')),
            ],
            options={
                'unique_together': {('teacher', 'year', 'subject')},
            },
        ),
    ]
