# Generated by Django 5.2.4 on 2025-07-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_subject_question_subject_studentsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='good',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='good',
            field=models.BooleanField(default=False),
        ),
    ]
