# Generated by Django 5.2.4 on 2025-07-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_answer_good_question_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='good_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='good_num',
            field=models.IntegerField(default=0),
        ),
    ]
