# Generated by Django 5.2.4 on 2025-07-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_goodanswermark_goodquestionmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
